/*
* Copyright (C) 2020 Andrew Reid and the ModelGUI Project <http://www.modelgui.org>
* 
* This file is part of ModelGUI[neuro] (mgui-neuro).
* 
* ModelGUI[neuro] is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* ModelGUI[neuro] is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with ModelGUI[neuro]. If not, see <http://www.gnu.org/licenses/>.
*/


package mgui.io.foreign.caret;

import java.io.File;

import mgui.interfaces.InterfaceEnvironment;


public class CaretSurfaceInfo {

	public String version = "5.403";
	//current date
	public String date = InterfaceEnvironment.getNow("EEE MMM dd HH:mm:ss yyyy");
	public String encoding = "BINARY";
	//coord file
	/***coord header:
	BeginHeader
	caret-version 5.402
	comment Coord Frame (stereotaxic space), orientation specified (3 Aug 2006 - DVE)	This file is the average of:	   Human_Buck_Case01.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case02.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case03.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case04.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.clean.73730.coord	   Human_Buck_Case05.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case06.R.F.RegToPALS_B12.LR.FIDUCIAL_SPM2.clean.73730.coord	   Human_Buck_Case07.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case08.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case09.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case10.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case11.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.73730.coord	   Human_Buck_Case12.R.M.RegToPALS_B12.LR.FIDUCIAL_SPM2.clean.73730.coord
	configuration_id FIDUCIAL
	coordframe_id SPM2
	date Thu Aug 3 21:54:45 2006
	encoding BINARY
	orientation LPI
	structure right
	topo_file Human.sphere_6.RIGHT_HEM.73730.topo
	EndHeader
	*/
	public String coord_comment = "Generated by ar.interface." + 
									InterfaceEnvironment.getVersion();
	public String coord_configuration_id = "FIDUCIAL";
	public String coord_coordframe_id = "SPM2";
	public String coord_orientation = "LPI";
	public String coord_structure = "right";
	//public String coord_topo_file = topoFile;
	
	//topo file
	/***topo header:
	BeginHeader
	comment closed topology, cleaned version
	date 28 May 2002 13:33:16
	encoding ASCII
	perimeter_id CLOSED
	resolution FULL
	sampling ORIGINAL
	EndHeader
	*/
	public String topo_comment = "Generated by ar.interface." + 
									InterfaceEnvironment.getVersion();
	//public String topo_encoding = "BINARY";
	public String topo_perimeter_id = "CLOSED";
	public String topo_resolution = "FULL";
	public String topo_sampling = "ORIGINAL";
	
}